#include "hash_tables.h"

/**
 * key_index - This function uses the hash_djb2 function to create the index at
 * which the key should be stored.
 * @key: the key generated by the hash function
 * @size: size of the hashtable
 * Return: index at which the key/value pair should be stored in the array
 */

unsigned long int key_index(const unsigned char *key, unsigned long int size)
{
	unsigned long int hash_num;

	hash_num = hash_djb2(key);

	hash_num = hash_num % size;

	return (hash_num);
}
